spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MSUtilisateur?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
 eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9093/eureka

