eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:9998/eureka:9093/eureka 
spring:
  cloud:
    gateway:
        routes:
          -id:microservice-projet
          uri:lb://microservice-projet 
          predicates:
            -path=/projet/**
          filtres:
            -RewritePath=/projet/(?<path>.*), /$\{path}  
